// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comment "douyin-tiktok/service/video/cmd/api/internal/handler/comment"
	favorite "douyin-tiktok/service/video/cmd/api/internal/handler/favorite"
	feed "douyin-tiktok/service/video/cmd/api/internal/handler/feed"
	"douyin-tiktok/service/video/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: feed.FeedHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/feed"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: favorite.FavoriteActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: favorite.ListFavoriteByUserIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/favorite"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: comment.CommentActionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: comment.ListCommentsByVideoIdHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/comment"),
	)
}
