// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userservice

import (
	"context"

	"douyin-tiktok/service/user/cmd/rpc/types"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CodeResp        = __.CodeResp
	GetInfoByIdReq  = __.GetInfoByIdReq
	GetInfoByIdResp = __.GetInfoByIdResp
	User            = __.User

	UserService interface {
		GetInfoById(ctx context.Context, in *GetInfoByIdReq, opts ...grpc.CallOption) (*GetInfoByIdResp, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

func (m *defaultUserService) GetInfoById(ctx context.Context, in *GetInfoByIdReq, opts ...grpc.CallOption) (*GetInfoByIdResp, error) {
	client := __.NewUserServiceClient(m.cli.Conn())
	return client.GetInfoById(ctx, in, opts...)
}
