// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	publish "douyin-tiktok/service/file/cmd/api/internal/handler/publish"
	"douyin-tiktok/service/file/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/action",
				Handler: publish.PublishActionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/douyin/publish"),
	)
}
