// Code generated by goctl. DO NOT EDIT.
package types

type TokenReq struct {
	Token string `json:"token" form:"token"`
}

type UserIdReq struct {
	TokenReq
	UserId int64 `json:"user_id" path:"user_id" form:"user_id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type FavoriteActionReq struct {
	VideoId    int64 `json:"video_id"`
	ActionType int32 `json:"action_type"`
}

type RelationActionReq struct {
	ToUserId   int64 `json:"to_user_id"`
	ActionType int32 `json:"action_type"`
}

type ChatReq struct {
	ToUserId   int64 `json:"to_user_id"`
	PreMsgTime int64 `json:"pre_msg_time"`
}

type MessageAction struct {
	TokenReq
	ToUserId   int64  `json:"to_user_id"`
	ActionType int32  `json:"action_type"`
	Content    string `json:"cOntent"`
}
