// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"douyin-tiktok/service/user/cmd/rpc/internal/logic"
	"douyin-tiktok/service/user/cmd/rpc/internal/svc"
	"douyin-tiktok/service/user/cmd/rpc/types"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) GetInfoByUserId(ctx context.Context, in *__.UserIdReq) (*__.GetInfoByUserIdResp, error) {
	l := logic.NewGetInfoByUserIdLogic(ctx, s.svcCtx)
	return l.GetInfoByUserId(in)
}
