// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package videoservice

import (
	"context"

	"douyin-tiktok/service/video/cmd/rpc/types"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetFavoriteAndFavoritedCntReq  = __.GetFavoriteAndFavoritedCntReq
	GetFavoriteAndFavoritedCntResp = __.GetFavoriteAndFavoritedCntResp

	VideoService interface {
		GetFavoriteAndFavoritedCnt(ctx context.Context, in *GetFavoriteAndFavoritedCntReq, opts ...grpc.CallOption) (*GetFavoriteAndFavoritedCntResp, error)
	}

	defaultVideoService struct {
		cli zrpc.Client
	}
)

func NewVideoService(cli zrpc.Client) VideoService {
	return &defaultVideoService{
		cli: cli,
	}
}

func (m *defaultVideoService) GetFavoriteAndFavoritedCnt(ctx context.Context, in *GetFavoriteAndFavoritedCntReq, opts ...grpc.CallOption) (*GetFavoriteAndFavoritedCntResp, error) {
	client := __.NewVideoServiceClient(m.cli.Conn())
	return client.GetFavoriteAndFavoritedCnt(ctx, in, opts...)
}
