// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"douyin-tiktok/service/video/cmd/rpc/internal/logic"
	"douyin-tiktok/service/video/cmd/rpc/internal/svc"
	"douyin-tiktok/service/video/cmd/rpc/types"
)

type CmdtyServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedCmdtyServiceServer
}

func NewCmdtyServiceServer(svcCtx *svc.ServiceContext) *CmdtyServiceServer {
	return &CmdtyServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CmdtyServiceServer) SaveVideo(ctx context.Context, in *__.SaveVideoReq) (*__.CodeResp, error) {
	l := logic.NewSaveVideoLogic(ctx, s.svcCtx)
	return l.SaveVideo(in)
}
