// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"douyin-tiktok/service/video/cmd/rpc/internal/logic"
	"douyin-tiktok/service/video/cmd/rpc/internal/svc"
	"douyin-tiktok/service/video/cmd/rpc/types"
)

type VideoServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedVideoServiceServer
}

func NewVideoServiceServer(svcCtx *svc.ServiceContext) *VideoServiceServer {
	return &VideoServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServiceServer) SaveVideo(ctx context.Context, in *__.SaveVideoReq) (*__.SaveVideoResp, error) {
	l := logic.NewSaveVideoLogic(ctx, s.svcCtx)
	return l.SaveVideo(in)
}
