// Code generated by goctl. DO NOT EDIT.
package types

type TokenReq struct {
	Token string `json:"token" form:"token"`
}

type FeedReq struct {
	LatestTime int64 `json:"latest_time"`
	TokenReq
}

type UserIdReq struct {
	TokenReq
	UserId int64 `json:"user_id" path:"user_id" form:"user_id"`
}

type FavoriteActionReq struct {
	TokenReq
	VideoId    int64 `json:"video_id"`
	ActionType int32 `json:"action_type"`
}

type CommentActionReq struct {
	TokenReq
	VideoId     int64  `json:"video_id"`
	ActionType  int32  `json:"action_type"`
	CommentText string `json:"comment_text"`
	CommentId   int64  `json:"comment_id"`
}

type VideoIdReq struct {
	TokenReq
	VideoId int64 `json:"videoId" form:"videoId" path:"videoId"`
}
